export const days = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];

export const timetableData = {
  Monday: [
    {
      id: "1",
      time: "08:00 AM",
      endTime: "08:45 AM",
      slot: 1,
      isCurrent: false,
      lectures: [
        {
          teacher: "Mr. Ahmed",
          subject: "Mathematics",
          className: "Class 6",
          section: "A",
        },
        {
          teacher: "Ms. Sara",
          subject: "English",
          className: "Class 8",
          section: "B",
        },
        {
          teacher: "Mr. Ali",
          subject: "Physics",
          className: "Class 10",
          section: "A",
        },
        {
          teacher: "Dr. Usman",
          subject: "Chemistry",
          className: "Class 9",
          section: "B",
        },
        {
          teacher: "Ms. Fatima",
          subject: "Biology",
          className: "Class 11",
          section: "A",
        },
      ],
    },
    {
      id: "2",
      time: "08:45 AM",
      endTime: "09:30 AM",
      slot: 2,
      isCurrent: true, // ← This slot will appear as the current/live slot
      lectures: [
        {
          teacher: "Mr. Khalid",
          subject: "Chemistry",
          className: "Class 7",
          section: "A",
        },
        {
          teacher: "Ms. Fatima",
          subject: "Biology",
          className: "Class 9",
          section: "B",
        },
        {
          teacher: "Dr. Usman",
          subject: "Physics",
          className: "Class 11",
          section: "A",
        },
        {
          teacher: "Ms. Ayesha",
          subject: "Computer Science",
          className: "Class 10",
          section: "B",
        },
      ],
    },
    {
      id: "3",
      time: "09:30 AM",
      endTime: "10:15 AM",
      slot: 3,
      isCurrent: false,
      lectures: [
        {
          teacher: "Mr. Hassan",
          subject: "History",
          className: "Class 6",
          section: "B",
        },
        {
          teacher: "Ms. Zara",
          subject: "English",
          className: "Class 7",
          section: "A",
        },
      ],
    },
    {
      id: "4",
      time: "10:15 AM",
      endTime: "10:45 AM",
      slot: 4,
      isBreak: true,
      lectures: [],
    },
    {
      id: "5",
      time: "10:45 AM",
      endTime: "11:30 AM",
      slot: 5,
      isCurrent: false,
      lectures: [
        {
          teacher: "Mr. Ahmed",
          subject: "Mathematics",
          className: "Class 8",
          section: "A",
        },
        {
          teacher: "Ms. Sara",
          subject: "English",
          className: "Class 9",
          section: "B",
        },
      ],
    },
  ],
  Tuesday: [
    {
      id: "1",
      time: "08:00 AM",
      endTime: "08:45 AM",
      slot: 1,
      isCurrent: false,
      lectures: [
        {
          teacher: "Ms. Fatima",
          subject: "Biology",
          className: "Class 10",
          section: "A",
        },
        {
          teacher: "Mr. Ali",
          subject: "Physics",
          className: "Class 8",
          section: "B",
        },
      ],
    },
    {
      id: "2",
      time: "08:45 AM",
      endTime: "09:30 AM",
      slot: 2,
      isCurrent: false,
      lectures: [
        {
          teacher: "Dr. Usman",
          subject: "Chemistry",
          className: "Class 9",
          section: "A",
        },
        {
          teacher: "Mr. Khalid",
          subject: "Mathematics",
          className: "Class 7",
          section: "B",
        },
        {
          teacher: "Ms. Sara",
          subject: "English",
          className: "Class 11",
          section: "A",
        },
      ],
    },
    {
      id: "3",
      time: "09:30 AM",
      endTime: "10:15 AM",
      slot: 3,
      isCurrent: false,
      lectures: [
        {
          teacher: "Mr. Hassan",
          subject: "History",
          className: "Class 8",
          section: "A",
        },
      ],
    },
    {
      id: "4",
      time: "10:15 AM",
      endTime: "10:45 AM",
      slot: 4,
      isBreak: true,
      lectures: [],
    },
    {
      id: "5",
      time: "10:45 AM",
      endTime: "11:30 AM",
      slot: 5,
      isCurrent: false,
      lectures: [
        {
          teacher: "Mr. Ahmed",
          subject: "Mathematics",
          className: "Class 9",
          section: "B",
        },
        {
          teacher: "Ms. Ayesha",
          subject: "Computer Science",
          className: "Class 10",
          section: "A",
        },
        {
          teacher: "Mr. Ali",
          subject: "Physics",
          className: "Class 7",
          section: "A",
        },
      ],
    },
  ],
  Wednesday: [
    {
      id: "1",
      time: "08:00 AM",
      endTime: "08:45 AM",
      slot: 1,
      isCurrent: false,
      lectures: [
        {
          teacher: "Mr. Ahmed",
          subject: "Mathematics",
          className: "Class 10",
          section: "A",
        },
        {
          teacher: "Ms. Sara",
          subject: "English",
          className: "Class 6",
          section: "B",
        },
      ],
    },
    {
      id: "2",
      time: "08:45 AM",
      endTime: "09:30 AM",
      slot: 2,
      isCurrent: false,
      lectures: [
        {
          teacher: "Mr. Ali",
          subject: "Physics",
          className: "Class 9",
          section: "A",
        },
        {
          teacher: "Ms. Fatima",
          subject: "Biology",
          className: "Class 8",
          section: "B",
        },
        {
          teacher: "Dr. Usman",
          subject: "Chemistry",
          className: "Class 11",
          section: "A",
        },
      ],
    },
    {
      id: "3",
      time: "09:30 AM",
      endTime: "10:15 AM",
      slot: 3,
      isCurrent: false,
      lectures: [
        {
          teacher: "Mr. Khalid",
          subject: "Mathematics",
          className: "Class 6",
          section: "A",
        },
      ],
    },
    {
      id: "4",
      time: "10:15 AM",
      endTime: "10:45 AM",
      slot: 4,
      isBreak: true,
      lectures: [],
    },
    {
      id: "5",
      time: "10:45 AM",
      endTime: "11:30 AM",
      slot: 5,
      isCurrent: false,
      lectures: [
        {
          teacher: "Ms. Ayesha",
          subject: "Computer Science",
          className: "Class 9",
          section: "B",
        },
        {
          teacher: "Mr. Hassan",
          subject: "History",
          className: "Class 10",
          section: "A",
        },
      ],
    },
  ],
  Thursday: [
    {
      id: "1",
      time: "08:00 AM",
      endTime: "08:45 AM",
      slot: 1,
      isCurrent: false,
      lectures: [
        {
          teacher: "Mr. Ahmed",
          subject: "Mathematics",
          className: "Class 7",
          section: "A",
        },
        {
          teacher: "Ms. Sara",
          subject: "English",
          className: "Class 9",
          section: "B",
        },
        {
          teacher: "Mr. Ali",
          subject: "Physics",
          className: "Class 11",
          section: "A",
        },
        {
          teacher: "Ms. Fatima",
          subject: "Biology",
          className: "Class 6",
          section: "A",
        },
      ],
    },
    {
      id: "2",
      time: "08:45 AM",
      endTime: "09:30 AM",
      slot: 2,
      isCurrent: false,
      lectures: [
        {
          teacher: "Dr. Usman",
          subject: "Chemistry",
          className: "Class 10",
          section: "B",
        },
        {
          teacher: "Mr. Khalid",
          subject: "Mathematics",
          className: "Class 8",
          section: "A",
        },
      ],
    },
    {
      id: "3",
      time: "09:30 AM",
      endTime: "10:15 AM",
      slot: 3,
      isCurrent: false,
      lectures: [
        {
          teacher: "Ms. Ayesha",
          subject: "Computer Science",
          className: "Class 7",
          section: "B",
        },
      ],
    },
    {
      id: "4",
      time: "10:15 AM",
      endTime: "10:45 AM",
      slot: 4,
      isBreak: true,
      lectures: [],
    },
    {
      id: "5",
      time: "10:45 AM",
      endTime: "11:30 AM",
      slot: 5,
      isCurrent: false,
      lectures: [
        {
          teacher: "Mr. Hassan",
          subject: "History",
          className: "Class 9",
          section: "A",
        },
        {
          teacher: "Mr. Ahmed",
          subject: "Mathematics",
          className: "Class 11",
          section: "B",
        },
      ],
    },
  ],
  Friday: [
    {
      id: "1",
      time: "08:00 AM",
      endTime: "08:45 AM",
      slot: 1,
      isCurrent: false,
      lectures: [
        {
          teacher: "Mr. Ali",
          subject: "Physics",
          className: "Class 6",
          section: "A",
        },
        {
          teacher: "Ms. Sara",
          subject: "English",
          className: "Class 7",
          section: "B",
        },
      ],
    },
    {
      id: "2",
      time: "08:45 AM",
      endTime: "09:30 AM",
      slot: 2,
      isCurrent: false,
      lectures: [
        {
          teacher: "Mr. Ahmed",
          subject: "Mathematics",
          className: "Class 10",
          section: "A",
        },
        {
          teacher: "Ms. Fatima",
          subject: "Biology",
          className: "Class 9",
          section: "B",
        },
      ],
    },
    {
      id: "3",
      time: "09:30 AM",
      endTime: "10:15 AM",
      slot: 3,
      isCurrent: false,
      lectures: [
        {
          teacher: "Dr. Usman",
          subject: "Chemistry",
          className: "Class 8",
          section: "A",
        },
        {
          teacher: "Mr. Khalid",
          subject: "Mathematics",
          className: "Class 11",
          section: "A",
        },
        {
          teacher: "Ms. Ayesha",
          subject: "Computer Science",
          className: "Class 6",
          section: "B",
        },
      ],
    },
    {
      id: "4",
      time: "10:15 AM",
      endTime: "10:45 AM",
      slot: 4,
      isBreak: true,
      lectures: [],
    },
    {
      id: "5",
      time: "10:45 AM",
      endTime: "11:30 AM",
      slot: 5,
      isCurrent: false,
      lectures: [
        {
          teacher: "Mr. Hassan",
          subject: "History",
          className: "Class 7",
          section: "A",
        },
      ],
    },
  ],
  Saturday: [
    {
      id: "1",
      time: "08:00 AM",
      endTime: "08:45 AM",
      slot: 1,
      isCurrent: false,
      lectures: [
        {
          teacher: "Ms. Sara",
          subject: "English",
          className: "Class 8",
          section: "A",
        },
        {
          teacher: "Mr. Ahmed",
          subject: "Mathematics",
          className: "Class 9",
          section: "B",
        },
      ],
    },
    {
      id: "2",
      time: "08:45 AM",
      endTime: "09:30 AM",
      slot: 2,
      isCurrent: false,
      lectures: [
        {
          teacher: "Mr. Ali",
          subject: "Physics",
          className: "Class 10",
          section: "A",
        },
      ],
    },
    {
      id: "3",
      time: "09:30 AM",
      endTime: "10:15 AM",
      slot: 3,
      isCurrent: false,
      lectures: [
        {
          teacher: "Ms. Fatima",
          subject: "Biology",
          className: "Class 7",
          section: "B",
        },
        {
          teacher: "Dr. Usman",
          subject: "Chemistry",
          className: "Class 11",
          section: "A",
        },
      ],
    },
    {
      id: "4",
      time: "10:15 AM",
      endTime: "10:45 AM",
      slot: 4,
      isBreak: true,
      lectures: [],
    },
    {
      id: "5",
      time: "10:45 AM",
      endTime: "11:30 AM",
      slot: 5,
      isCurrent: false,
      lectures: [
        {
          teacher: "Mr. Khalid",
          subject: "Mathematics",
          className: "Class 6",
          section: "A",
        },
        {
          teacher: "Ms. Ayesha",
          subject: "Computer Science",
          className: "Class 8",
          section: "B",
        },
      ],
    },
  ],
};
