export const teacherData = {
  id: "teacher-1",
  name: "Ahmed Khan",
  // Convert subjects to the format expected by TeacherCard
  subjects: [
    { name: "Mathematics", className: "Class 6", section: "A" },
    { name: "Physics", className: "Class 9", section: "B" },
    { name: "Mathematics", className: "Class 10", section: "A" },
    { name: "English", className: "Class 8", section: "B" },
    { name: "Computer Science", className: "Class 9", section: "A" },
    { name: "Physics", className: "Class 11", section: "A" },
    { name: "English", className: "Class 7", section: "A" },
    { name: "Computer Science", className: "Class 10", section: "A" },
  ],
  // Add class teacher information if applicable
  classTeacher: {
    className: "Class 6",
    section: "A",
    subject: "Mathematics",
  },
  // Keep the timetable data for the grid
  timetable: {
    Monday: [
      {
        slot: 1,
        time: "08:00-08:45",
        subject: "Mathematics",
        class: "Class 6",
        section: "A",
      },
      {
        slot: 2,
        time: "08:45-09:30",
        subject: "Physics",
        class: "Class 9",
        section: "B",
      },
      {
        slot: 3,
        time: "09:30-10:15",
        subject: null,
        class: null,
        section: null,
      },
      {
        slot: 4,
        time: "10:15-10:45",
        subject: "Break",
        class: null,
        section: null,
        isBreak: true,
      },
      {
        slot: 5,
        time: "10:45-11:30",
        subject: "Mathematics",
        class: "Class 10",
        section: "A",
      },
      {
        slot: 6,
        time: "11:30-12:15",
        subject: "English",
        class: "Class 8",
        section: "B",
      },
    ],
    Tuesday: [
      {
        slot: 1,
        time: "08:00-08:45",
        subject: "Physics",
        class: "Class 9",
        section: "A",
      },
      {
        slot: 2,
        time: "08:45-09:30",
        subject: null,
        class: null,
        section: null,
      },
      {
        slot: 3,
        time: "09:30-10:15",
        subject: "Mathematics",
        class: "Class 10",
        section: "B",
      },
      {
        slot: 4,
        time: "10:15-10:45",
        subject: "Break",
        class: null,
        section: null,
        isBreak: true,
      },
      {
        slot: 5,
        time: "10:45-11:30",
        subject: "Physics",
        class: "Class 11",
        section: "A",
      },
      {
        slot: 6,
        time: "11:30-12:15",
        subject: "English",
        class: "Class 7",
        section: "A",
      },
    ],
    Wednesday: [
      {
        slot: 1,
        time: "08:00-08:45",
        subject: "English",
        class: "Class 7",
        section: "B",
      },
      {
        slot: 2,
        time: "08:45-09:30",
        subject: "Mathematics",
        class: "Class 9",
        section: "B",
      },
      {
        slot: 3,
        time: "09:30-10:15",
        subject: null,
        class: null,
        section: null,
      },
      {
        slot: 4,
        time: "10:15-10:45",
        subject: "Break",
        class: null,
        section: null,
        isBreak: true,
      },
      {
        slot: 5,
        time: "10:45-11:30",
        subject: "Physics",
        class: "Class 10",
        section: "A",
      },
      {
        slot: 6,
        time: "11:30-12:15",
        subject: "Mathematics",
        class: "Class 6",
        section: "A",
      },
    ],
    Thursday: [
      {
        slot: 1,
        time: "08:00-08:45",
        subject: "Mathematics",
        class: "Class 8",
        section: "A",
      },
      {
        slot: 2,
        time: "08:45-09:30",
        subject: "English",
        class: "Class 9",
        section: "A",
      },
      {
        slot: 3,
        time: "09:30-10:15",
        subject: "Physics",
        class: "Class 11",
        section: "B",
      },
      {
        slot: 4,
        time: "10:15-10:45",
        subject: "Break",
        class: null,
        section: null,
        isBreak: true,
      },
      {
        slot: 5,
        time: "10:45-11:30",
        subject: null,
        class: null,
        section: null,
      },
      {
        slot: 6,
        time: "11:30-12:15",
        subject: "Computer Science",
        class: "Class 10",
        section: "A",
      },
    ],
    Friday: [
      {
        slot: 1,
        time: "08:00-08:45",
        subject: "Physics",
        class: "Class 10",
        section: "B",
      },
      {
        slot: 2,
        time: "08:45-09:30",
        subject: null,
        class: null,
        section: null,
      },
      {
        slot: 3,
        time: "09:30-10:15",
        subject: "Mathematics",
        class: "Class 7",
        section: "A",
      },
      {
        slot: 4,
        time: "10:15-10:45",
        subject: "Break",
        class: null,
        section: null,
        isBreak: true,
      },
      {
        slot: 5,
        time: "10:45-11:30",
        subject: "English",
        class: "Class 9",
        section: "B",
      },
      {
        slot: 6,
        time: "11:30-12:15",
        subject: "Physics",
        class: "Class 8",
        section: "A",
      },
    ],
    Saturday: [
      {
        slot: 1,
        time: "08:00-08:45",
        subject: "Mathematics",
        class: "Class 11",
        section: "A",
      },
      {
        slot: 2,
        time: "08:45-09:30",
        subject: "Computer Science",
        class: "Class 9",
        section: "B",
      },
      {
        slot: 3,
        time: "09:30-10:15",
        subject: null,
        class: null,
        section: null,
      },
      {
        slot: 4,
        time: "10:15-10:45",
        subject: "Break",
        class: null,
        section: null,
        isBreak: true,
      },
      {
        slot: 5,
        time: "10:45-11:30",
        subject: "Mathematics",
        class: "Class 8",
        section: "B",
      },
      {
        slot: 6,
        time: "11:30-12:15",
        subject: "English",
        class: "Class 10",
        section: "A",
      },
    ],
  },
};
